### ISSUE TITLE
mechanical design files (ovc3a)

### ISSUE THREAD

**Issue by jpaulos** [osrf/ovc#23]
Do simple mechanical drawings (dimensions, camera centers, hole placement) exist for either the ovc3a board or perhaps a reference design housing which would have the same information?

I can manually click around and extract this information from the KiCAD project -- is there a better way?

If such a document were created, where should it live in the repository?

**Comment by luca-della-vedova** [comment]
Hi @jpaulos !

For now there is no such document. I think the easiest way to get basic information about the board (dimensions, hole placement, cameras baseline etc.) is to use the "Add dimension" feature of kicad.
If you wanted to create a document for this I would probably add all the dimensions to a custom layer then print the PCB by excluding all the unnecessary ones (i.e. copper), you should get a reasonable 2d drawing.

If you want 3d information instead, you might want to export the 3d model of the board as a step file and use a CAD software to edit it (i.e. freecad). We used the latter way in the past to verify board stacks and it works quite well.

Cheers,
/Luca

**Comment by jpaulos** [comment]
Thanks for the tip about the "Add dimension" tool, through it seems like the ability to snap to centers that aren't on-grid is limited. I ended up doing this with a pencil.
