### ISSUE TITLE
About the camera used in ovc3b

### ISSUE THREAD

**Issue by Winifred-oss** [osrf/ovc#26]
Hi,
We are trying to reproduce the ovc3b these days. The  project ovc3b provide us the lens holder PT-LH010M and the CMOS image sensor AR0144CS. However, we still don't know the version of the camera lens. Can you share the information about the camera lens with us? 

Waiting for your reply!

**Comment by luca-della-vedova** [comment]
Hi!

This is one of the questions where the answer is "it depends", I recommend thinking about your application and whether you need a wide field of view or a good range. Those lenses are very cheap so you can buy a few and play with them to see what works best.
Just make sure you buy a lens which is for the imager format!

Cheers,
/Luca
