### ISSUE TITLE
The question about TE0820 in OVC3b.

### ISSUE THREAD

**Issue by Jingjing1219** [osrf/ovc#27]
Hi,
The model you used in the ovc3b camera board TE0820-03-3BE21FA is no longer available. I want to know if it can be replaced with 4DE21FA without changing the circuit (because our PCB board has been made, only this chip is missing.)

Cheers,
Jingjing

**Comment by luca-della-vedova** [comment]
That module seems to use the 4EV version of the FPGA, you can but you would need to rebuild your bitfiles for this chip and wouldn't be able to use the prebuilt ones (since for now we only support the 3EG chip).

**Comment by Jingjing1219** [comment]
Many thanks.
And sorry, we don’t know FPGA at present, and we need follow-up learning (such as rebuild the bitfiles). So, is there a perfect alternative model for TE0820-03-3BE21FA?

**Comment by luca-della-vedova** [comment]
The [TE0821](https://shop.trenz-electronic.de/en/TE0821-01-3BE21FA-MPSoC-Module-with-Xilinx-Zynq-UltraScale-ZU3EG-1-2-GByte-DDR4-SDRAM-4-x-5-cm?c=156) is basically the same module

**Comment by Jingjing1219** [comment]
Sorry, I want to confirm, do you mean we can use TE0821-01-3BE21FA instead of TE0820-03-3BE21FA without changing the circuit? 
Or should we wait until TE0820-03-3BE21FA is available?
Many thanks.

**Comment by luca-della-vedova** [comment]
I'm not sure on the top of my head (would double check their specs) but I think they are basically the same module

**Comment by Jingjing1219** [comment]
Many thanks.
