### ISSUE TITLE
About the vision algorithm 

### ISSUE THREAD

**Issue by Winifred-oss** [osrf/ovc#28]
We find many repositories in https://osrf.github.io/ovc/software.html can not be open, such as Real-time Semantic Segmentation, Stereo Image Splitter, GPU Accelerated Dense Stereo Disparity Estimation. More about the visual algorithms used in your experiment  [The Open Vision Computer: An Integrated Sensing and Compute System for Mobile Robots](https://arxiv.org/abs/1809.07674v1) are also not found in  http://open.vision.computer.  
Thus, we wonder if  we could get your visual algorithm to duplicate your experiment (vision-based autonomous navigation of uav) after our hardware is finished? 
Looking forward to your reply.

**Comment by luca-della-vedova** [comment]
Hi,

I'm not sure what happened to the algorithm repos, they were developed by the people at the GRASP lab in University of Pennsylvania, as you can see from the paper however, most of the algorithms run on the ARM cores, meaning that they would be able to run with any ROS compatible camera.
The main benefit of the OVC for that application was the feature extraction happening in FPGA which, being one of the most computationally expensive tasks, made the pipeline much faster.
In general however autonomous navigation is a _hard task_ especially in a UAV and I personally think there isn't any quick and easy way to implement it.
I would recommend starting from each building block and studying the available options, then trying to assemble them one by one.
The camera (i.e. OVC) is only one of the blocks.

Good luck!

**Comment by iandouglas96** [comment]
As luca noted, currently the autonomy pipeline described in the paper is not open-sourced (and it is not in a state such that it could be easily integrated anyway).  The state estimation portion is, and is available here: https://github.com/KumarRobotics/msckf_vio, though it is not specific to the ovc.  The planner and controller are not publicly available.
