### ISSUE TITLE
Information request on OVC3 device configuration.

### ISSUE THREAD

**Issue by Han-sok** [osrf/ovc#33]
Hello, 

I am currently working on your OVC3, more specifically "OPEN VISION COMPUTER REV 3A (MARCH 2019)"
I have a board with me.

My plan is to develop an FPGA system to perform my own application, but it looks like OVC3 does not have JTAG connectivity.
When I tried to connect USB-C port to the PC, Vivado's hardware manager did not detect any device.
**What are the available options to configure FPGA if I want to load my logic design to OVC3?**

I read Trenz's specsheet and manual and found this.
![image](https://user-images.githubusercontent.com/39740632/100863724-3836a500-3452-11eb-8969-c073cf7aaf4c.png)
According to this, only boot from SD/flash(eMMC) is possible. (Assuming you are using default firmware in CPLD.)
If that's true, **what are the available debug options to probe signals in the FPGA?**

I am not asking for specific tutorial for any of these question.
(Though if you can briefly explain me how to do that it would be appreciated.)

**Also I want to know how this switch is mapped to the boot mode selection functionality.**
![image](https://user-images.githubusercontent.com/39740632/100866534-07f10580-3456-11eb-81c5-d05af28eb44d.png)
Clearly, JTAGEN is for selecting a USB connection to either FPGA/CLPD.
MODE is for SD/eMMC selection.
NOSEQ looks like doing the same functionality that is specified in the above screenshot.
(Selecting JTAG mode when the firmware in the last column is installed I guess?)
But then, what is the USER pin used for?

So my question is...
1. Information on available FPGA configuration options.
2. Information on available debug options.
3. Information on mode switch.

Thank you!

Best regards,
Han-sok

**Comment by luca-della-vedova** [comment]
Hi Han-sok!

> My plan is to develop an FPGA system to perform my own application, but it looks like OVC3 does not have JTAG connectivity.
> When I tried to connect USB-C port to the PC, Vivado's hardware manager did not detect any device.
> What are the available options to configure FPGA if I want to load my logic design to OVC3?

The OVC3 does have JTAG connectivity, it is brought out to the J6 pin header so you would need a programmer (such as the [Xilinx Platform Cable](https://www.xilinx.com/products/boards-and-kits/hw-usb-ii-g.html) and connect the wires to the pin header.
In alternative if you are running Linux onboard you can use the sysfs interface to program the FPGA with your bitfile (it is usually what I do), or just embed the bitfile in your BOOT.bin bootable image.

> If that's true, what are the available debug options to probe signals in the FPGA?

Currently the only way to probe signals is by having the Xilinx programmer I mentioned above connected to the JTAG pins.

> But then, what is the USER pin used for?

The USER pin is used for GPIO and is exported to Linux. One of the main uses is for flashing the OVC, there is a script that runs on boot in the Ubuntu image that reads the USER pin and depending on its position will reflash the OVC (download the latest binaries and overwrite the rootfs / bootable images stored in the eMMC / QSPI flash). The pin has this functionality only when booting from SD card though, so if you are booting from eMMC you can feel free to use it for your own applications.

Cheers!
/Luca

**Comment by Han-sok** [comment]
Thank you so much for a quick response, Luca.

I see. But I have one more thing I want to ask.
I check the board but J6 does not have a pin connector attached. So, do I need to solder the pin connecter on my own? Or is it a different pin by any chance? I attached a photo for your reference.
![image](https://user-images.githubusercontent.com/39740632/100916960-bcf5e300-3493-11eb-9ede-5f8eb1694ac7.png)

Best,
Han-sok

**Comment by Han-sok** [comment]
Oh! I found it. 

There's another small J6 tag on the other side of the device.
So this is the one you were talking about, right?
![image](https://user-images.githubusercontent.com/39740632/100918030-3215e800-3495-11eb-99dd-f5cebd9a5480.png)

Best,
Han-sok

**Comment by fcladera** [comment]
yes!

**Comment by Han-sok** [comment]
Got it. Thank you for the clarification. I will populate the pins with socket first and get back to you if I have any problem.

**Comment by fcladera** [comment]
@Han-sok can we close this?

**Comment by Han-sok** [comment]
Sure. Please do so.

Thank you

Best regards,
Han-sok
